EH.rawMaterials = {
    [1] = {
        808,
        4482,
        4995,
        5820,
        23103,
        23104,
        23105,
        23133,
        23134,
        23135,
    },
    [2] = {
        793,
        800,
        812,
        4448,
        4464,
        4478,
        6020,
        23095,
        23097,
        23129,
        23130,
        23131,
        23142,
        23143,
        33217,
        33218,
        33219,
        33220,
    },
    [3] = {
        45806,
        45807,
        45808,
        45809,
        45810,
        45811,
        45812,
        45813,
        45814,
        45815,
        45816,
        45817,
        45818,
        45819,
        45820,
        45821,
        45822,
        45823,
        45824,
        45825,
        45826,
        45827,
        45828,
        45829,
        45830,
        45831,
        45832,
        45833,
        45834,
        45835,
        45836,
        45837,
        45838,
        45839,
        45840,
        45841,
        45842,
        45843,
        45844,
        45845,
        45846,
        45847,
        45848,
        45849,
        45850,
        45851,
        45852,
        45853,
        45854,
        45855,
        45856,
        45857,
        54248,
        54253,
        54289,
        54294,
        54297,
        54299,
        54306,
        54330,
        54331,
        54342,
        54373,
        54374,
        54375,
        54481,
        54482,
    },
    [4] = {
        883,
        1187,
        4570,
        23265,
        23266,
        23267,
        23268,
        30148,
        30149,
        30151,
        30152,
        30153,
        30154,
        30155,
        30156,
        30157,
        30158,
        30159,
        30160,
        30161,
        30162,
        30163,
        30164,
        30165,
        30166,
    },
    -- If this is an empty set then the format does not erase previous
    -- saved data
    [5] = {
    },
    [6] = {
        521,
        802,
        818,
        4439,
        23117,
        23118,
        23119,
        23137,
        23138,
    },
}

EH.validNodes = {
    ["en"] = {
        "Ashtree",
        "Aspect Rune",
        "Backpack",
        "Barrel",
        "Barrel (Burnt)",
        "Barrels",
        "Barrels (Burnt)",
        "Basket",
        "Beech",
        "Birch",
        "Blessed Thistle",
        "Book",
        "Book Stack",
        "Books",
        "Bookshelf",
        "Bottle",
        "Bottles",
        "Bread",
        "Bugloss",
        "Cabinet",
        "Calcinium Ore", -- Verified
        "Carrots",
        "Cheese",
        "Columbine",
        "Corn Flower",
        "Cotton",
        "Crate",
        "Crate (Burnt)",
        "Crates",
        "Crates (Burnt)",
        "Cup",
        "Cupboard",
        "Cups",
        "Desk",
        "Dragonthorn",
        "Dresser",
        "Drink",
        "Dwarven Ore",
        "Ebonthread",
        "Ebony Ore",
        "Emetic Russula",
        "Entoloma",
        "Essence Rune",
        "Famin Flower",
        "Fish",
        "Flax",
        "Food",
        "Galatite Ore",
        "Goblet",
        "Grain",
        "Grapes",
        "Heavy Sack",
        "Hickory",
        "High Iron Ore",
        "Imp Stool",
        "Iron Ore",
        "Iron Weed",
        "Jar",
        "Jug",
        "Jute",
        "Kreshweed",
        "Lady's Smock",
        "Luminous Russula",
        "Mahogany",
        "Maple",
        "Moonstone Ore",
        "Mountain Flower",
        "Mug",
        "Namira's Rot",
        "Nightstand",
        "Nightwood",
        "Nirnroot",
        "Oak",
        "Orichalc Ore", -- Needs Verification
        "Orichalcum Ore",
        "Pot",
        "Potency Rune",
        "Produce",
        "Pure Water",
        "QA Clickable",
        "QA Clickable Apples",
        "QA lowlevel provision test",
        "Quicksilver Ore",
        "Radish",
        "Sack",
        "Saint's Hair",
        "Silverweed",
        "Spidersilk",
        "Stinkhorn",
        "Tomb Urn",
        "Trunk",
        "Urn",
        "Vase",
        "Violet Copninus",
        "Void Bloom",
        "Voidstone Ore",
        "Wardrobe",
        "Water Hyacinth",
        "Water Skin",
        "White Cap",
        "Wine Rack",
        "Wormwood",
        "Yew",
    },
    ["de"] = {
        "Eschenholz",
        "Aspektrune",
        "Rucksack",
        "Fass",
        "Fass (versengt)",
        "Fässer",
        "Fässer (versengt)",
        "Korb",
        "Buche",
        "Birke",
        "Benediktenkraut",
        "Buch",
        "Buchstapel",
        "Bücher",
        "Bücherregal",
        "Flasche",
        "Flaschen",
        "Brot",
        "Wolfsauge",
        "Schrank",
        "Kalciniumerz",
        "Möhren",
        "Käse",
        "Akelei",
        "Kornblume",
        "Baumwolle",
        "Kiste",
        "Kiste (versengt)",
        "Kisten",
        "Kisten (versengt)",
        "Tasse",
        "Schrank",
        "Tassen",
        "Schreibtisch",
        "Drachendorn",
        "Kommode",
        "Getränk",
        "Dwemererz",
        "Ebenseide",
        "Ebenerz",
        "Speitäubling",
        "Glöckling",
        "Essenzrune",
        "Hungersnotblume",
        "Fischen",
        "Flachs",
        "Essen",
        "Galatiterz",
        "Becher",
        "Getreide",
        "Weintrauben",
        "Schwerer Sack",
        "Hickoryholz",
        "Feineisenerz",
        "Koboldschemel",
        "Eisenerz",
        "Eisenkraut",
        "Gefäß",
        "Krug",
        "Jute", -- Verified, it's just Jute
        "Kreshweed",
        "Wiesenschaumkraut",
        "Leuchttäubling",
        "Mahagoniholz",
        "Ahornholz",
        "Mondsteinerz",
        "Bergblume",
        "Becher",
        "Namira's Fäulnis",
        "Nachttisch",
        "Nachtholz",
        "Nirnwurz",
        "Eiche",
        "Orichalc Ore", -- Needs Verification
        "Oreichalkoserz", -- Orichalcum Ore
        "Topf",
        "Machtrune",
        "Produkt",
        "Reines Wasser",
        "QA Clickable",
        "QA Clickable Apples",
        "QA lowlevel provision test",
        "Quicksilver Ore",
        "Radieschen",
        "Sack",
        "Heiliges Haar",
        "Silverweed",
        "Spinnenseide",
        "Stinkmorchel",
        "Urnengrab",
        "Stamm", -- Needs Verification
        "Urne",
        "Vase",
        "Violetter Coprinus",
        "Leere Blüte",
        "Leerensteinerz",
        "Kleiderschrank",
        "Wasserhyazinthe",
        "Wasserhaut",
        "Weiße Kappe",
        "Weinregal",
        "Wermut",
        "Eibenholz",
    },
    -- Pot, Jute, Jar, Hickory, Grain, Cabinet and Entoloma are the same names in French
    ["fr"] = {
        "Frêne",
        "Rune d'Aspect",
        "Sac à dos",
        "Tonneau",
        "Tonneau (brûlé)",
        "Tonneaux",
        "Tonneaux (brûlés)",
        "Panier",
        "Hêtre",
        "Bouleau",
        "Chardon Béni",
        "Livre",
        "Pile de livres",
        "Livres",
        "Étagère",
        "Bouteille",
        "Bouteilles",
        "Pain",
        "Noctuelle",
        "Cabinet",
        "Minerai de Calcinium",
        "Carrottes",
        "Fromage",
        "Ancolie",
        "Bleuet",
        "Coton",
        "Caisse",
        "Caisse (brûlée)",
        "Caisses",
        "Caisses (brûlées)",
        "Tasse",
        "Commode",
        "Tasses",
        "Bureau",
        "Épine-de-Dragon",
        "Buffet",
        "Boisson",
        "Minerai Dwemer",
        "Fil d'Ebonite",
        "Minerai d'Ebonite",
        "Russule Emetique",
        "Entoloma",
        "Rune D'essence",
        "Famin Flower",
        "Poisson",
        "Lin",
        "Nourriture",
        "Minerai de Galatite",
        "Chope",
        "Grain",
        "Raisin",
        "Sac Lourd",
        "Hickory",
        "Minerai de Fer Noble",
        "Pied-de-Lutin",
        "Minerai de Fer",
        "Herbe de fer",
        "Jar",
        "Pichet",
        "Jute",
        "Fibre de Kresh",
        "Cardamine des Prés",
        "Russule Phosphorescente",
        "Acajou",
        "Érable",
        "Pierre de lune",
        "Lys des Cimes",
        "Choppe",
        "Truffe de Namira",
        "Table de chevet",
        "Bois de nuit",
        "Nirnrave",
        "Chêne",
        "Orichalc Ore", -- Needs Verification
        "Minerai D'orichalque",  -- Orichalcum Ore
        "Pot",
        "Rune de Puissance",
        "Céréales",
        "Eau Pure",
        "QA Clickable",
        "QA Clickable Apples",
        "QA lowlevel provision test",
        "Quicksilver Ore",
        "Radis",
        "Sac",
        "Saint's Hair",
        "Herbe d'argent",
        "Toile D'araignée",
        "Mutinus Elégans",
        "Urne tombale",
        "Coffre",
        "Urne",
        "Vase",
        "Coprin Violet",
        "Tissu de Vide",
        "Minerai de Pierre de Vide",
        "Garde-robe",
        "Jacinthe D'eau",
        "Outre d'Eau",
        "Chapeau Blanc",
        "Casier ŕ bouteilles",
        "Absinthe",
        "If",
    }
}

function EH.GetTradeskillByMaterial(id)
    id = tonumber(id)
    local profession = 0

    for tsId, tsData in pairs(EH.rawMaterials) do
        for key, value in pairs(tsData) do
            if value == id then
                profession = tsId
                return profession
            end
        end
    end
    return profession
end

function EH.IsValidNode(name)
    for k, v in pairs(EH.validNodes[EH.language]) do
        if string.lower(v) == string.lower(name) then
            return true
        end
    end

    return false
end
